### ISSUE TITLE
使用_BackfaceTex获得模型厚度有错

### ISSUE THREAD

**Issue by Magic-Wan** [yangrc1234/Unity-Simple-SSR#1]
我取消了大佬对获取模型厚度的注释，想使用_BackfaceTex获得模型厚度，但是运行发现会得到奇怪的结果，希望大佬给个指导

**Comment by yangrc1234** [comment]
不好意思，这个我已经很久没维护了，估计我自己都不认得里面的代码了，还是你自己研究下吧Orz。

Btw这种算厚度的方案似乎并没有真的游戏在用，毕竟会导致翻倍的drawcall，仅仅为了一个后处理效果不太值得。

**Comment by Magic-Wan** [comment]
多谢多谢
